import importlib
import subprocess
import sys

from portalocker import __main__


def test_combine_uses_sys_executable(tmp_path, monkeypatch):
    """B6: the combined-file smoke run must use ``sys.executable``.

    Hardcoding ``python3`` breaks on Windows venvs (no ``python3.exe``).
    """
    calls: list[list[str]] = []

    def spy(cmd, *args, **kwargs):
        calls.append(list(cmd))
        return subprocess.CompletedProcess(cmd, 0)

    monkeypatch.setattr(subprocess, 'run', spy)
    output_file = tmp_path / 'combined.py'
    __main__.main(['combine', '--output-file', str(output_file)])

    assert [sys.executable, str(output_file)] in calls


def test_combined(tmpdir):
    output_file = tmpdir.join('combined.py')
    __main__.main(['combine', '--output-file', output_file.strpath])

    print(output_file)  # noqa: T201
    print('#################')  # noqa: T201
    print(output_file.read())  # noqa: T201
    print('#################')  # noqa: T201

    sys.path.append(output_file.dirname)
    # The `combined` module is generated by the `combine` call above, so
    # static analysis can't resolve it; import it dynamically instead.
    combined = importlib.import_module('combined')

    assert hasattr(combined, 'lock')
