import importlib
import sys

from portalocker import __main__


def test_combined(tmpdir):
    output_file = tmpdir.join('combined.py')
    __main__.main(['combine', '--output-file', output_file.strpath])

    print(output_file)  # noqa: T201
    print('#################')  # noqa: T201
    print(output_file.read())  # noqa: T201
    print('#################')  # noqa: T201

    sys.path.append(output_file.dirname)
    # The `combined` module is generated by the `combine` call above, so
    # static analysis can't resolve it; import it dynamically instead.
    combined = importlib.import_module('combined')

    assert hasattr(combined, 'lock')
