name: lint

on:
  push:
  pull_request:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Generate dynamic matrix
        id: matrix
        uses: coactions/dynamic-matrix@v4.1.0
        with:
          min_python: '3.9'
          other_names: |
            lint
            pyright
            mypy
          platforms: linux

  run-tox:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.tox.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.tox.python_version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e '.[tests]'
      - name: Run tox for ${{ matrix.tox.name }}
        run: |
          tox -e ${{ matrix.tox.name }}
