name: lint

on:
  push:
  pull_request:

env:
  FORCE_COLOR: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Define all your tox environments that you want to run in parallel
        tox_env:
          - 'py39'
          - 'py310'
          - 'py311'
          - 'py312'
          - 'ruff'
          - 'mypy'  # Or a more specific name if you have multiple mypy setups
          - 'pyright'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (for running tox)
        uses: actions/setup-python@v5
        with:
          # Use a consistent, recent Python version to install and run tox.
          # Tox will use the 'basepython' setting from tox.ini for each environment.
          python-version: '3.11'
          cache: 'pip' # Cache pip dependencies

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Python version (of tox runner)
        run: python --version

      - name: Run tox -e ${{ matrix.tox_env }}
        run: tox -e ${{ matrix.tox_env }}
