name: CI with dynamic tox matrix

on:
  push:
  pull_request:

env:
  FORCE_COLOR: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dynamic_matrix_step.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate tox environment matrix
        id: dynamic_matrix_step # Clear ID for the step producing the output
        uses: coactions/dynamic-matrix@v4
        with:
        # Ensure this points to your tox configuration file if it's not auto-detected
        # config-file: 'tox.toml' # Or 'tox.ini'
        # Add other parameters like factors-allow-list if needed

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # This is the critical line (ensure it's correctly indented)
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python for tox runner
        uses: actions/setup-python@v5
        with:
          # This Python version is used to run tox itself.
          # Tox will then use 'base_python' from your tox.toml for each environment.
          # matrix.python_version could be used if dynamic-matrix provides it AND you want it here.
          python-version: ${{ matrix.python_version || '3.11' }}
          cache: 'pip'

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Python version (of tox runner)
        run: python --version

      - name: Run tox -e ${{ matrix.tox_env }}
        # 'matrix.tox_env' assumes coactions/dynamic-matrix outputs 'tox_env' as the environment key.
        # Adjust if the key is different (e.g., 'env', 'factor').
        # You can inspect the output of the 'generate-matrix' job to be sure.
        run: tox -e ${{ matrix.tox_env }}
